trigger:
  branches:
    include:
      - main

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ACR-Connection'
  imageRepository: 'frontend-app'
  containerRegistry: 'myfrontendacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Azure App Service details
  azureSubscription: 'Azure-Connection'
  appName: 'my-frontend-app'
  resourceGroupName: 'your-resource-group-name'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  pool: 
    vmImage: ubuntu-latest  # Pool defined at stage level for inheritance
  jobs:
  - job: Build
    displayName: Build Docker Image
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: Build  # Ensures sequential execution after Build stage
  condition: succeeded()
  pool: 
    vmImage: ubuntu-latest  # Pool defined at stage level for inheritance
  jobs:
  - deployment: Deploy
    displayName: Deploy to App Service
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy to Azure App Service
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appName)
              containers: $(containerRegistry)/$(imageRepository):$(tag)