name: Deploy to Azure Load Balanced VMs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: myapp

jobs:
  get-infrastructure-info:
    runs-on: ubuntu-latest
    outputs:
      registry_server: ${{ steps.get-info.outputs.registry_server }}
      vm_ips: ${{ steps.get-info.outputs.vm_ips }}
      resource_group: ${{ steps.get-info.outputs.resource_group }}
    steps:
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Get Infrastructure Info
      id: get-info
      run: |
        RG_NAME="rg-webapp-lb"
        
        # Get ACR info
        ACR_NAME=$(az acr list -g $RG_NAME --query '[0].name' -o tsv)
        REGISTRY_SERVER="${ACR_NAME}.azurecr.io"
        
        # Get VM IPs as JSON array
        VM_IPS=$(az vm list-ip-addresses -g $RG_NAME --query '[].virtualMachine.network.publicIpAddresses[0].ipAddress' -o json)
        
        echo "registry_server=$REGISTRY_SERVER" >> $GITHUB_OUTPUT
        echo "vm_ips=$VM_IPS" >> $GITHUB_OUTPUT
        echo "resource_group=$RG_NAME" >> $GITHUB_OUTPUT
        
        echo "Registry Server: $REGISTRY_SERVER"
        echo "VM IPs: $VM_IPS"

  build-and-push:
    runs-on: ubuntu-latest
    needs: get-infrastructure-info
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push Docker image
      run: |
        REGISTRY_SERVER="${{ needs.get-infrastructure-info.outputs.registry_server }}"
        
        # Login to ACR
        az acr login --name ${REGISTRY_SERVER%.*}
        
        # Build and push image
        docker build -t $REGISTRY_SERVER/${{ env.IMAGE_NAME }}:latest .
        docker push $REGISTRY_SERVER/${{ env.IMAGE_NAME }}:latest
        
        echo "Image pushed: $REGISTRY_SERVER/${{ env.IMAGE_NAME }}:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: [get-infrastructure-info, build-and-push]
    strategy:
      matrix:
        vm_ip: ${{ fromJson(needs.get-infrastructure-info.outputs.vm_ips) }}
    steps:
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Get ACR credentials
      id: acr-creds
      run: |
        RG_NAME="${{ needs.get-infrastructure-info.outputs.resource_group }}"
        ACR_NAME=$(az acr list -g $RG_NAME --query '[0].name' -o tsv)
        
        ACR_USERNAME=$(az acr credential show --name $ACR_NAME --query username -o tsv)
        ACR_PASSWORD=$(az acr credential show --name $ACR_NAME --query passwords[0].value -o tsv)
        
        echo "acr_username=$ACR_USERNAME" >> $GITHUB_OUTPUT
        echo "::add-mask::$ACR_PASSWORD"
        echo "acr_password=$ACR_PASSWORD" >> $GITHUB_OUTPUT
    
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/azure_vm_key
        chmod 600 ~/.ssh/azure_vm_key
        ssh-keyscan -H ${{ matrix.vm_ip }} >> ~/.ssh/known_hosts
    
    - name: Deploy to VM
      run: |
        REGISTRY_SERVER="${{ needs.get-infrastructure-info.outputs.registry_server }}"
        
        ssh -i ~/.ssh/azure_vm_key azureuser@${{ matrix.vm_ip }} << 'EOF'
          # Login to ACR on VM
          echo "${{ steps.acr-creds.outputs.acr_password }}" | docker login ${{ needs.get-infrastructure-info.outputs.registry_server }} -u ${{ steps.acr-creds.outputs.acr_username }} --password-stdin
          
          # Pull and run new container
          docker pull ${{ needs.get-infrastructure-info.outputs.registry_server }}/${{ env.IMAGE_NAME }}:latest
          
          # Stop existing container
          docker stop myapp 2>/dev/null || true
          docker
